### ISSUE TITLE
Errors Fix

### ISSUE THREAD

**Issue by kv4nt** [bfday/yii2-payture-module#1]
PaytureInPay

init function ...

```
if ($response && empty($response->ErrCode))
        {
            self::$_sessionId = $response->SessionId;
        }
```

add **&& empty($response->ErrCode)**

-------
не всегда response положительный приходит. соответственно SessionId может и не быть

**Comment by bfday** [comment]
Добавил. Только в обратное последовательности.

**Comment by kv4nt** [comment]
спасибо
